version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dzenCode

  app:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - '5000:5000'
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dzenCode
      - DB_PORT=5432
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?schema=public"

